# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &admin_guifuentes8 age19uj05y090zwe0dkhkv654dhfgxqc7247m0dtqxadl2plymfzpq2sz0c2v6
  - &server_guifuentes8 age15p3h8ep7rvw0e3yanenyqvx3jktwflytm2efyjrjh8uzf8duqsfq6dttm2
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_guifuentes8
          - *server_guifuentes8
