# Catppuccin themes for Spotify-player

[[themes]]
name = "Tokyo-Night-Storm"
[themes.palette]
background = "#24283b"
foreground = "#c0caf5"
black= "#1d202f"
blue= "#7aa2f7"
cyan= "#7dcfff"
green= "#33cccc"
magenta= "#bb9af7"
red= "#f7768e"
white= "#a9b1d6"
yellow= "#e0af68"
bright_black= "#414868"
bright_blue= "#7aa2f7"
bright_cyan= "#7dcfff"
bright_green= "#33cccc"
bright_magenta= "#bb9af7"
bright_red= "#f7768e"
bright_white= "#c0caf5"
bright_yellow= "#e0af68"
selection_background = "#364a82"
selection_foreground = "#c0caf5"

[themes.component_style]
block_title = { fg = "Magenta"  }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "Black", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }


[[themes]]
name = "Catppuccin-latte"
[themes.palette]
background = "#EFF1F5"
foreground = "#4C4F69"
black = "#EFF1F5"
blue = "#1E66F5"
cyan = "#04A5E5"
green = "#40A02B"
magenta = "#8839EF"
red = "#D20F39"
white = "#4C4F69"
yellow = "#DF8E1D"
bright_black = "#EFF1F5"
bright_blue = "#1E66F5"
bright_cyan = "#04A5E5"
bright_green = "#40A02B"
bright_magenta = "#8839EF"
bright_red = "#D20F39"
bright_white = "#4C4F69"
bright_yellow = "#DF8E1D"
selection_background = "#CCD0DA"
selection_foreground = "#4C4F69"

[themes.component_style]
block_title = { fg = "Magenta"  }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "Black", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }


[[themes]]
name = "Catppuccin-frappe"
[themes.palette]
background = "#303446"
foreground = "#C6D0F5"
black = "#303446"
blue = "#8CAAEE"
cyan = "#89DCEB"
green = "#A6D189"
magenta = "#CA9EE6"
red = "#E78284"
white = "#C6D0F5"
yellow = "#E5C890"
bright_black = "#303446"
bright_blue = "#8CAAEE"
bright_cyan = "#89DCEB"
bright_green = "#A6D189"
bright_magenta = "#CA9EE6"
bright_red = "#E78284"
bright_white = "#C6D0F5"
bright_yellow = "#E5C890"
selection_background = "#414559"
selection_foreground = "#C6D0F5"

[themes.component_style]
block_title = { fg = "Magenta"  }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "Black", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }


[[themes]]
name = "Catppuccin-macchiato"
[themes.palette]
background = "#24273A"
foreground = "#CAD3F5"
black = "#24273A"
blue = "#8AADF4"
cyan = "#91D7E3"
green = "#A6DA95"
magenta = "#C6A0F6"
red = "#ED8796"
white = "#CAD3F5"
yellow = "#EED49F"
bright_black = "#24273A"
bright_blue = "#8AADF4"
bright_cyan = "#91D7E3"
bright_green = "#A6DA95"
bright_magenta = "#C6A0F6"
bright_red = "#ED8796"
bright_white = "#CAD3F5"
bright_yellow = "#EED49F"
selection_background = "#363A4F00"
selection_foreground = "#CAD3F5"

[themes.component_style]
block_title = { fg = "Magenta"  }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "Black", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
