# Catppuccin themes for Spotify-player

[[themes]]
name = "Carbonfox"
[themes.palette]
background = "#161616"
foreground = "#f2f4f8"
black= "#282828"
blue= "#78a9ff"
cyan= "#08bdba"
green= "#25be6a"
magenta= "#be95ff"
red= "#ee5396"
white= "#dfdfe0"
yellow= "#33b1ff"
bright_black= "#484848"
bright_blue= "#8cb6ff"
bright_cyan= "#2dc7c4"
bright_green= "#46c880"
bright_magenta= "#c8a5ff"
bright_red= "#f16da6"
bright_white= "#e4e4e5"
bright_yellow= "#52bdff"
selection_background = "#2a2a2a"
selection_foreground = "#f2f4f8"

[themes.component_style]
block_title = { fg = "Magenta"  }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "Black", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }


