[[themes]]
name = "Catppuccin-frappe"
[themes.palette]
background = "#303446"
foreground = "#C6D0F5"
black = "#303446"
blue = "#8CAAEE"
cyan = "#89DCEB"
green = "#A6D189"
magenta = "#CA9EE6"
red = "#E78284"
white = "#C6D0F5"
yellow = "#E5C890"
bright_black = "#303446"
bright_blue = "#8CAAEE"
bright_cyan = "#89DCEB"
bright_green = "#A6D189"
bright_magenta = "#CA9EE6"
bright_red = "#E78284"
bright_white = "#C6D0F5"
bright_yellow = "#E5C890"
selection_background = "#414559"
selection_foreground = "#C6D0F5"

[themes.component_style]
block_title = { fg = "Magenta"  }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "Black", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }